fix

diff --git a/docker/contrib/tomcat.patch b/docker/contrib/tomcat.patch
--- a/docker/contrib/tomcat.patch
+++ b/docker/contrib/tomcat.patch
@@ -1,117 +1,61 @@
 diff --new-file -ru ../original/bin/catalina.sh ./bin/catalina.sh
 --- ../original/bin/catalina.sh	2019-11-22 11:42:32.000000000 -0800
-+++ ./bin/catalina.sh	2020-03-09 13:49:25.000000000 -0700
-@@ -354,7 +354,14 @@
++++ ./bin/catalina.sh	2020-03-09 13:58:37.000000000 -0700
+@@ -354,7 +354,7 @@
          echo "Using Security Manager"
        fi
        shift
 -      exec "$_RUNJDB" "$LOGGING_CONFIG" $LOGGING_MANAGER $JAVA_OPTS $CATALINA_OPTS \
-+      # Set Proxy Host Settings Only for Production 
-+      if [ ! -z PROXY_HOST ] 
-+      then 
-+        sed -i 's/<!--ProxyHostForProd//' $CATALINA_HOME/conf/server.xml
-+        sed -i 's/ProxyHostForProd-->//' $CATALINA_HOME/conf/server.xml
-+        echo "Add ProxyHost configuration if PROXY_HOST"
-+      fi
 +      exec "$_RUNJDB" "$LOGGING_CONFIG" $LOGGING_MANAGER $JAVA_OPTS $DEFAULT_CATALINA_OPTS $CATALINA_OPTS \
          -D$ENDORSED_PROP="$JAVA_ENDORSED_DIRS" \
          -classpath "$CLASSPATH" \
          -sourcepath "$CATALINA_HOME"/../../java \
-@@ -365,7 +372,14 @@
+@@ -365,7 +365,7 @@
          -Djava.io.tmpdir="$CATALINA_TMPDIR" \
          org.apache.catalina.startup.Bootstrap "$@" start
      else
 -      exec "$_RUNJDB" "$LOGGING_CONFIG" $LOGGING_MANAGER $JAVA_OPTS $CATALINA_OPTS \
-+    # Set Proxy Host Settings Only for Production 
-+      if [ ! -z PROXY_HOST ] 
-+      then 
-+        sed -i 's/<!--ProxyHostForProd//' $CATALINA_HOME/conf/server.xml
-+        sed -i 's/ProxyHostForProd-->//' $CATALINA_HOME/conf/server.xml
-+        echo "Add ProxyHost configuration if PROXY_HOST"
-+      fi
 +      exec "$_RUNJDB" "$LOGGING_CONFIG" $LOGGING_MANAGER $JAVA_OPTS $DEFAULT_CATALINA_OPTS $CATALINA_OPTS \
          -D$ENDORSED_PROP="$JAVA_ENDORSED_DIRS" \
          -classpath "$CLASSPATH" \
          -sourcepath "$CATALINA_HOME"/../../java \
-@@ -384,7 +398,14 @@
+@@ -384,7 +384,7 @@
        echo "Using Security Manager"
      fi
      shift
 -    eval exec "\"$_RUNJAVA\"" "\"$LOGGING_CONFIG\"" $LOGGING_MANAGER $JAVA_OPTS $CATALINA_OPTS \
-+    # Set Proxy Host Settings Only for Production 
-+      if [ ! -z PROXY_HOST ] 
-+      then 
-+        sed -i 's/<!--ProxyHostForProd//' $CATALINA_HOME/conf/server.xml
-+        sed -i 's/ProxyHostForProd-->//' $CATALINA_HOME/conf/server.xml
-+        echo "Add ProxyHost configuration if PROXY_HOST"
-+      fi
 +    eval exec "\"$_RUNJAVA\"" "\"$LOGGING_CONFIG\"" $LOGGING_MANAGER $JAVA_OPTS $DEFAULT_CATALINA_OPTS $CATALINA_OPTS \
        -D$ENDORSED_PROP="\"$JAVA_ENDORSED_DIRS\"" \
        -classpath "\"$CLASSPATH\"" \
        -Djava.security.manager \
-@@ -394,7 +415,14 @@
+@@ -394,7 +394,7 @@
        -Djava.io.tmpdir="\"$CATALINA_TMPDIR\"" \
        org.apache.catalina.startup.Bootstrap "$@" start
    else
 -    eval exec "\"$_RUNJAVA\"" "\"$LOGGING_CONFIG\"" $LOGGING_MANAGER $JAVA_OPTS $CATALINA_OPTS \
-+  # Set Proxy Host Settings Only for Production 
-+      if [ ! -z PROXY_HOST ] 
-+      then 
-+        sed -i 's/<!--ProxyHostForProd//' $CATALINA_HOME/conf/server.xml
-+        sed -i 's/ProxyHostForProd-->//' $CATALINA_HOME/conf/server.xml
-+        echo "Add ProxyHost configuration if PROXY_HOST"
-+      fi
 +    eval exec "\"$_RUNJAVA\"" "\"$LOGGING_CONFIG\"" $LOGGING_MANAGER $JAVA_OPTS $DEFAULT_CATALINA_OPTS $CATALINA_OPTS \
        -D$ENDORSED_PROP="\"$JAVA_ENDORSED_DIRS\"" \
        -classpath "\"$CLASSPATH\"" \
        -Dcatalina.base="\"$CATALINA_BASE\"" \
-@@ -429,6 +457,13 @@
-               fi
-             fi
-           fi
-+          # Set Proxy Host Settings Only for Production 
-+      if [ ! -z PROXY_HOST ] 
-+      then 
-+        sed -i 's/<!--ProxyHostForProd//' $CATALINA_HOME/conf/server.xml
-+        sed -i 's/ProxyHostForProd-->//' $CATALINA_HOME/conf/server.xml
-+        echo "Add ProxyHost configuration if PROXY_HOST"
-+      fi
-         else
-           echo "Unable to read PID file. Start aborted."
-           exit 1
-@@ -452,7 +487,14 @@
+@@ -452,7 +452,7 @@
        echo "Using Security Manager"
      fi
      shift
 -    eval $_NOHUP "\"$_RUNJAVA\"" "\"$LOGGING_CONFIG\"" $LOGGING_MANAGER $JAVA_OPTS $CATALINA_OPTS \
-+    # Set Proxy Host Settings Only for Production 
-+      if [ ! -z PROXY_HOST ] 
-+      then 
-+        sed -i 's/<!--ProxyHostForProd//' $CATALINA_HOME/conf/server.xml
-+        sed -i 's/ProxyHostForProd-->//' $CATALINA_HOME/conf/server.xml
-+        echo "Add ProxyHost configuration if PROXY_HOST"
-+      fi
 +    eval $_NOHUP "\"$_RUNJAVA\"" "\"$LOGGING_CONFIG\"" $LOGGING_MANAGER $JAVA_OPTS $DEFAULT_CATALINA_OPTS $CATALINA_OPTS \
        -D$ENDORSED_PROP="\"$JAVA_ENDORSED_DIRS\"" \
        -classpath "\"$CLASSPATH\"" \
        -Djava.security.manager \
-@@ -464,7 +506,14 @@
+@@ -464,7 +464,7 @@
        >> "$CATALINA_OUT" 2>&1 "&"
  
    else
 -    eval $_NOHUP "\"$_RUNJAVA\"" "\"$LOGGING_CONFIG\"" $LOGGING_MANAGER $JAVA_OPTS $CATALINA_OPTS \
-+  # Set Proxy Host Settings Only for Production 
-+      if [ ! -z PROXY_HOST ] 
-+      then 
-+        sed -i 's/<!--ProxyHostForProd//' $CATALINA_HOME/conf/server.xml
-+        sed -i 's/ProxyHostForProd-->//' $CATALINA_HOME/conf/server.xml
-+        echo "Add ProxyHost configuration if PROXY_HOST"
-+      fi
 +    eval $_NOHUP "\"$_RUNJAVA\"" "\"$LOGGING_CONFIG\"" $LOGGING_MANAGER $JAVA_OPTS $DEFAULT_CATALINA_OPTS $CATALINA_OPTS \
        -D$ENDORSED_PROP="\"$JAVA_ENDORSED_DIRS\"" \
        -classpath "\"$CLASSPATH\"" \
        -Dcatalina.base="\"$CATALINA_BASE\"" \
-@@ -649,3 +698,6 @@
+@@ -649,3 +649,6 @@
    exit 1
  
  fi
@@ -127,6 +71,79 @@ diff --new-file -ru ../original/bin/setenv.sh ./bin/setenv.sh
 +CATALINA_OPTS="-XshowSettings:vm  -XX:MaxRAM=$(( $(cat /sys/fs/cgroup/memory/memory.limit_in_bytes) - ( 1024 * 10) )) -XX:MaxRAMPercentage=100.0 $CATALINA_OPTS"
 +CATALINA_OPTS="-javaagent:$CATALINA_HOME/bin/jolokia-jvm-1.6.2-agent.jar=port=7070,host=localhost,discoveryEnabled=false $CATALINA_OPTS"
 +DEFAULT_CATALINA_OPTS='-Dorg.apache.tomcat.util.digester.PROPERTY_SOURCE=org.apache.tomcat.util.digester.Digester\$EnvironmentPropertySource -Djava.security.egd=file:/dev/./urandom'
+diff --new-file -ru ../original/bin/startup.sh ./bin/startup.sh
+--- ../original/bin/startup.sh	1969-12-31 16:00:00.000000000 -0800
++++ ./bin/startup.sh	2020-03-09 13:58:43.000000000 -0700
+@@ -0,0 +1,68 @@
++#!/usr/bin/env bash
++
++# Licensed to the Apache Software Foundation (ASF) under one or more
++# contributor license agreements.  See the NOTICE file distributed with
++# this work for additional information regarding copyright ownership.
++# The ASF licenses this file to You under the Apache License, Version 2.0
++# (the "License"); you may not use this file except in compliance with
++# the License.  You may obtain a copy of the License at
++#
++#     http://www.apache.org/licenses/LICENSE-2.0
++#
++# Unless required by applicable law or agreed to in writing, software
++# distributed under the License is distributed on an "AS IS" BASIS,
++# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
++# See the License for the specific language governing permissions and
++# limitations under the License.
++
++# -----------------------------------------------------------------------------
++# Start Script for the CATALINA Server
++# -----------------------------------------------------------------------------
++
++# Better OS/400 detection: see Bugzilla 31132
++os400=false
++case "`uname`" in
++OS400*) os400=true;;
++esac
++
++# resolve links - $0 may be a softlink
++PRG="$0"
++
++while [ -h "$PRG" ] ; do
++  ls=`ls -ld "$PRG"`
++  link=`expr "$ls" : '.*-> \(.*\)$'`
++  if expr "$link" : '/.*' > /dev/null; then
++    PRG="$link"
++  else
++    PRG=`dirname "$PRG"`/"$link"
++  fi
++done
++
++PRGDIR=`dirname "$PRG"`
++EXECUTABLE=catalina.sh
++
++# Check that target executable exists
++if $os400; then
++  # -x will Only work on the os400 if the files are:
++  # 1. owned by the user
++  # 2. owned by the PRIMARY group of the user
++  # this will not work if the user belongs in secondary groups
++  eval
++else
++  if [ ! -x "$PRGDIR"/"$EXECUTABLE" ]; then
++    echo "Cannot find $PRGDIR/$EXECUTABLE"
++    echo "The file is absent or does not have execute permission"
++    echo "This file is needed to run this program"
++    exit 1
++  fi
++fi
++
++# Set Proxy Host Settings Only for Production 
++if [ ! -z PROXY_HOST ] 
++then 
++  sed -i 's/<!--ProxyHostForProd//' $CATALINA_HOME/conf/server.xml
++  sed -i 's/ProxyHostForProd-->//' $CATALINA_HOME/conf/server.xml
++  echo "Add ProxyHost configuration if"
++fi
++
++exec "$PRGDIR"/"$EXECUTABLE" start "$@"
+\ No newline at end of file
 diff --new-file -ru ../original/bin/unpack-webapps.sh ./bin/unpack-webapps.sh
 --- ../original/bin/unpack-webapps.sh	1969-12-31 16:00:00.000000000 -0800
 +++ ./bin/unpack-webapps.sh	2020-03-09 11:48:58.000000000 -0700
